
services:
  alice-lightningd:
    command:
      --bitcoin-rpcconnect=bitcoind
      --bitcoin-rpcpassword=btcpass
      --bitcoin-rpcport=18443
      --bitcoin-rpcuser=btcuser
      --database-upgrade=true
      --grpc-host=0.0.0.0
      --grpc-port=8888
      --lightning-dir=/data/.lightning
      --log-level=debug
      --network=regtest
    depends_on:
      - bitcoind
      - lsp-lightningd
      - miner
    image: lightningd-alice
    networks:
      - breez-internal
      - public-lightning
      - miner
    volumes:
      - alice-lightningd:/data/.lightning
      - lsp-lightningd:/data/.lightning-lsp

  bitcoind:
    command:
      -addresstype=bech32
      -debug=mempool
      -debug=rpc
      -fallbackfee=0.00000253
      -logtimestamps
      -nolisten
      -regtest
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcpassword=btcpass
      -rpcuser=btcuser
      -rest
      -server
      -txindex
    image: bitcoind
    networks:
      - breez-internal
      # - greenlight-internal
      - lsp-internal
      - miner
    restart: always
    volumes:
      - bitcoin:/data/.bitcoin
    ports:
      - 18443:18443

  breez-server:
    depends_on:
      - breez-server-postgres
      - breez-server-redis
    environment:
      - BITCOIND_HOST=bitcoind
      - BITCOIND_PASSWORD=btcpass
      - BITCOIND_PORT=18443
      - BITCOIND_USER=btcuser
      - CHAIN_API_SERVERS=[{"server_type":"MEMPOOL_SPACE","server_base_url":"https://mempool.space/api/"},{"server_type":"MEMPOOL_SPACE","server_base_url":"https://mempool.emzy.de/api/"}]
      - DATABASE_URL=postgresql://server-user:server-pass@breez-server-postgres/server-db?sslmode=disable
      - POSTGRES_HOST=breez-server-postgres
      - PGPASSWORD=server-pass
      - POSTGRES_PORT=5432
      - POSTGRES_USER=server-user
      - POSTGRES_DB=server-db
      - GRPC_LISTEN_ADDRESS=0.0.0.0:8888
      - HTTP_LISTEN_ADDRESS=0.0.0.0:9999
      - LSP_CONFIG={"lspd":{"${LSP_ID}":{"server":"lspd:8888","token":"${LSPD_TOKEN}","noTLS":true}}}
      - LSP_ID=${LSP_ID}
      - LSP_TOKEN=${LSPD_TOKEN}
      - NETWORK=regtest
      - NO_LIQUID=true
      - NO_LND=true
      - NO_RATELIMITS=true
      - NO_SUBSWAP=true
      - PUBLIC_CHANNEL_TOKENS={}
      - REDIS_URL=breez-server-redis:6379
      - REDIS_DB=1
      - SDK_API_KEY=${SDK_API_KEY}
      - SWAPD_ADDRESS=swapd:58049
    image: breez-server
    networks:
      - breez-internal
      - breez-lsp
      - public-internet
    ports:
      - 8888:8888

  breez-server-postgres:
    environment:
      - POSTGRES_DB=server-db
      - POSTGRES_PASSWORD=server-pass
      - POSTGRES_USER=server-user
    image: postgres:16
    networks:
      - breez-internal
    restart: always
    volumes:
      - server-postgres:/var/lib/postgresql/data

  breez-server-redis:
    image: redis:7.2.4
    networks:
      - breez-internal
    restart: always

  # greenlight-node1:
  #   command:
  #     --bitcoin-rpcconnect=bitcoind:18443
  #     --bitcoin-rpcpassword=btcpass
  #     --bitcoin-rpcuser=btcuser
  #     --disable-plugin=cln-grpc
  #     --disable-plugin=commando
  #     --important-plugin=/usr/local/bin/gl-plugin
  #     --lightning-dir=/data/.lightning/
  #     --log-level=debug
  #     --log-timestamps=false
  #     --network=regtest
  #     --subdaemon=hsmd:/usr/local/bin/gl-signerproxy
  #   depends_on:
  #     - bitcoind
  #     - greenlight-node1-scheduler
  #   environment:
  #     - CLN_PLUGIN_LOG=gl_plugin=trace,gl_signerproxy=trace,cln_client=trace,cln_grpc=trace,cln_rpc=trace,info
  #     - GL_CERT_PATH=/data/.scheduler/cert
  #     - GL_NODE_BIND=0.0.0.0:8888
  #     - GL_NODE_NETWORK=regtest
  #     - GL_PLUGIN_CLIENTCA_PATH=/data/.scheduler/cert/ca.pem
  #     - RUST_LOG=gl_client=trace,gl_signerproxy=trace,gl_plugin=trace,cln_plugin=trace,cln_rpc=trace,cln_grpc=trace,info
  #   image: lightningd-greenlight
  #   networks:
  #     - greenlight-internal
  #     - public-lightning
  #     - public-internet
  #   volumes:
  #     - greenlight-node1:/data/.lightning
  #     - greenlight-node1-scheduler:/data/.scheduler

  # greenlight-node1-scheduler:
  #   command:
  #     --address=0.0.0.0:8888
  #     --cert-path=/data/.scheduler/cert
  #     --init-path=/data/.scheduler/init
  #     --node-grpc-uri=node1-greenlight:8888
  #   image: greenlight-scheduler
  #   networks:
  #     - public-internet
  #   volumes:
  #     - greenlight-node1-scheduler:/data/.scheduler

  lsp-lightningd:
    command:
      --bitcoin-rpcconnect=bitcoind
      --bitcoin-rpcpassword=btcpass
      --bitcoin-rpcport=18443
      --bitcoin-rpcuser=btcuser
      --database-upgrade=true
      --dev-allowdustreserve=true
      --dev-force-privkey=7d1886ac8c00ef7eb53ddc645dab2fe8a48f09940f8a49305aed3253bc49117f
      --developer
      --grpc-host=0.0.0.0
      --grpc-port=8888
      --lightning-dir=/data/.lightning
      --log-level=debug
      --lsp-listen=0.0.0.0:12312
      --max-concurrent-htlcs=30
      --network=regtest
      --plugin=/usr/local/bin/lspd_cln_plugin
    depends_on:
      - bitcoind
      - miner
    image: lightningd-lsp
    networks:
      # call the host for lightningd 'cln', so the grpc certificate has a valid host. 
      lsp-internal:
        aliases:
          - cln
      public-lightning:
      miner:
    ports:
      - 19846:19846
    volumes:
      - lsp-lightningd:/data/.lightning

  lspd:
    depends_on:
      - lsp-lightningd
      - lspd-postgres
    environment:
      - AUTO_MIGRATE_DATABASE=false
      - DATABASE_URL=postgresql://lspd-user:lspd-pass@lspd-postgres/lspd-db?sslmode=disable
      - POSTGRES_HOST=lspd-postgres
      - PGPASSWORD=lspd-pass
      - POSTGRES_PORT=5432
      - POSTGRES_USER=lspd-user
      - POSTGRES_DB=lspd-db
      - LSPD_PRIVATE_KEY="31d1f2a8daf0c04c78d73e2ff0673d6f1a394dc41ae5b319b7623a6139766766"
      - LSPD_TOKEN=${LSPD_TOKEN}
      - NODES=[{"tokens":["${LSPD_TOKEN}"],"host":"localhost:19846","lspdPrivateKey":"5df76d23bf7a00a1c66c1fafc860f55f26005ec11cd88efeba92813567da63eb","baseFeeMsat":"1000","feeRate":"0.00001","timeLockDelta":"6","additionalChannelCapacity":"50000","cln":{"pluginAddress":"cln:12312","grpcAddress":"cln:8888","caCert":"/data/.lightning/regtest/ca.pem","clientCert":"/data/.lightning/regtest/client.pem","clientKey":"/data/.lightning/regtest/client-key.pem"}}]
    image: lspd
    networks:
      - breez-lsp
      - lsp-internal
    volumes:
      - lsp-lightningd:/data/.lightning

  lspd-postgres:
    environment:
      - POSTGRES_DB=lspd-db
      - POSTGRES_PASSWORD=lspd-pass
      - POSTGRES_USER=lspd-user
    image: postgres:16
    networks:
      - lsp-internal
    restart: always
    volumes:
      - lspd-postgres:/var/lib/postgresql/data
  
  miner:
    command:
      --address=0.0.0.0:8888
      --bitcoin-rpcconnect=bitcoind:18443
      --bitcoin-rpcpassword=btcpass
      --bitcoin-rpcuser=btcuser
      --block-interval-secs=600
    depends_on:
      - bitcoind
    image: miner
    networks:
      - miner

  rgs-nginx:
    image: nginx:latest
    volumes:
      - ./rgs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - rgs-data:/data:ro
    depends_on:
      - rgs-server
    ports:
      - 8011:8011

  rgs-server:
    image: rgs-server
    volumes:
      - rgs-data:/usr/src/app/res
    links:
      - bitcoind
      - rgs-postgres
    depends_on:
      - lsp-lightningd
      - rgs-postgres
    environment:
      - BITCOIN_REST_DOMAIN=bitcoind
      - BITCOIN_REST_PATH=/rest/
      - BITCOIN_REST_PORT=18443
      - LN_PEERS=0361984fe2a03cc594e97de423bf461096dd26a52e77feda68510377f360e430d4@lsp-lightningd:19846
      - RAPID_GOSSIP_SYNC_SERVER_DB_HOST=rgs-postgres
      - RAPID_GOSSIP_SYNC_SERVER_DB_NAME=ln_graph_sync
      - RAPID_GOSSIP_SYNC_SERVER_DB_PASSWORD=docker
      - RAPID_GOSSIP_SYNC_SERVER_DB_USER=lightning-rgs
      - RAPID_GOSSIP_SYNC_SERVER_NETWORK=regtest
    command: ['sh', '-c', 'echo Give some time for LSP to start ... && sleep 5 && rapid-gossip-sync-server']
    networks:
      - miner
      - public-lightning
      - rgs-internal

  rgs-postgres:
    image: postgres:16
    volumes:
      - rgs-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ln_graph_sync
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=lightning-rgs
    networks:
      - rgs-internal
    ports:
      - 5432:5432

  swapd:
    image: swapd
    command:
      --address=0.0.0.0:58049
      --auto-migrate
      --network=regtest
      --cln-grpc-address=http://alice-lightningd:8888
      --cln-grpc-ca-cert=/data/.lightning/regtest/ca.pem
      --cln-grpc-client-cert=/data/.lightning/regtest/client.pem
      --cln-grpc-client-key=/data/.lightning/regtest/client-key.pem
      --log-level=swapd=debug,info
      --db-url=postgresql://swapd-user:swapd-pass@swapd-postgres/swapd-db?sslmode=disable
      --bitcoind-rpc-address=http://bitcoind:18443
      --bitcoind-rpc-user=btcuser
      --bitcoind-rpc-password=btcpass
      --chain-poll-interval-seconds=5
    depends_on:
      - bitcoind
      - swapd-postgres
    networks:
      - breez-internal
    volumes:
      - alice-lightningd:/data/.lightning

  swapd-postgres:
    image: postgres:16
    volumes:
      - swapd-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=swapd-db
      - POSTGRES_PASSWORD=swapd-pass
      - POSTGRES_USER=swapd-user
    networks:
      - breez-internal

  electrs:
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoind:18443
      - --cookie
      - btcuser:btcpass
      - --http-addr
      - 0.0.0.0:30000
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      - bitcoind
    entrypoint:
      - /build/electrs
    image: ghcr.io/vulpemventures/electrs:latest
    networks:
      - miner
    ports:
      - 30000:30000

networks:
  # greenlight-internal:
  breez-internal:
  breez-lsp:
  lsp-internal:
  miner:
  public-internet:
  public-lightning:
  rgs-internal:

volumes:
  # greenlight-node1-scheduler:
  # greenlight-node1:
  alice-lightningd:
  bitcoin:
  electrs-data:
  lsp-lightningd:
  lspd-postgres:
  rgs-data:
  rgs-postgres: null
  server-postgres:
  swapd-postgres:
