[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
bitcoincore-rpc = "0.19.0"
clap = { version = "4.5.4", features = ["derive"] }
serde = "1.0.202"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-util = "0.7.14"
